name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: crykn/copy_folder_to_another_repo_action@v1.0.6
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'cam634.github.io/Webpages'
        destination_repo: 'cam634/Practice'
        user_email: 'cam6352@gmail.com'
        user_name: 'cam634'
        commit_msg: '[GHA] Update the test files.'
