on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'Webpages'
        destination_repo: 'cam634/Practice'
        destination_folder: 'test-dir'
        user_email: 'cam6352@gmail.com'
        user_name: 'cam634'
        commit_message: 'A custom message for the commit'
